Introdução

Neste projeto, será realizada uma análise exploratória de um conjunto de dados contendo anúncios de veículos usados. O objetivo é identificar padrões e relações entre as principais características dos veículos e seus preços.

Durante a análise, serão investigadas variáveis como marca, ano de fabricação, quilometragem e preço dos veículos. Também serão tratados valores ausentes e possíveis valores discrepantes que possam distorcer os resultados.

A partir dos dados preparados, serão construídas visualizações para compreender melhor a distribuição dos preços, comparar os preços entre diferentes marcas e anos de fabricação e analisar a relação entre quilometragem e preço.

Os resultados desta análise servirão de base para a construção de um dashboard interativo, desenvolvido posteriormente com Streamlit.

In [18]:
# Importando bibliotecas

import pandas as pd
import plotly.express as px
import streamlit as st

# Ajustando as configurações de exibição do pandas

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [19]:
# Carregando o dataset de veículos

vehicles = pd.read_csv(r'C:\sprint5dir\sprint_5_project-Dashboard\vehicles.csv')

# Exibindo informações sobre o dataset

vehicles.info()
print()
vehicles.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  str
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   42258 non-null  str
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  str
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), str(7)
memory usage: 7.7 MB

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28
5,14990,2014.0,chrysler 300,excellent,6.0,gas,57954.0,automatic,sedan,black,1.0,2018-06-20,15
6,12990,2015.0,toyota camry,excellent,4.0,gas,79212.0,automatic,sedan,white,NaN,2018-12-27,73
7,15990,2013.0,honda pilot,excellent,6.0,gas,109473.0,automatic,SUV,black,1.0,2019-01-07,68
8,11500,2012.0,kia sorento,excellent,4.0,gas,104174.0,automatic,SUV,NaN,1.0,2018-07-16,19
9,9200,2008.0,honda pilot,excellent,NaN,gas,147191.0,automatic,SUV,blue,1.0,2019-02-15,17

In [20]:
# Verificando duplicatas e valores nulos no dataset

print(vehicles.duplicated().sum())
print()
print(vehicles.isnull().sum())

0

price               0
model_year       3619
model               0
condition           0
cylinders        5260
fuel                0
odometer         7892
transmission        0
type                0
paint_color      9267
is_4wd          25953
date_posted         0
days_listed         0
dtype: int64

In [21]:
# Analisando estatísticas descritivas dos preços dos carros do dataset

print(vehicles['price'].min(), vehicles['price'].max())

1 375000

In [22]:
# Analisando a quantidade de veículos com preço igual a 1 e exibindo os 15 veículos mais baratos

print((vehicles['price'] == 1).sum())
print()
vehicles.sort_values(by='price').head(15)

798

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
12186,1,2015.0,ford edge,excellent,6.0,gas,24897.0,automatic,SUV,black,1.0,2018-12-24,45
40638,1,NaN,chevrolet silverado,excellent,8.0,gas,140582.0,automatic,truck,silver,NaN,2018-05-03,25
14644,1,2018.0,chevrolet tahoe,excellent,8.0,gas,7726.0,automatic,SUV,black,NaN,2018-12-04,16
49385,1,2016.0,chevrolet silverado 1500,good,6.0,gas,NaN,automatic,truck,white,NaN,2018-11-30,10
11298,1,2018.0,chevrolet tahoe,excellent,8.0,gas,1003.0,automatic,SUV,black,1.0,2018-06-12,42
11297,1,2015.0,ford edge,excellent,6.0,gas,24897.0,automatic,SUV,black,1.0,2018-08-19,19
11296,1,2015.0,toyota sienna,excellent,6.0,gas,NaN,automatic,van,black,1.0,2018-08-29,5
11295,1,2018.0,gmc acadia,excellent,10.0,gas,26152.0,other,SUV,NaN,1.0,2018-11-14,37
16868,1,2016.0,dodge charger,excellent,10.0,gas,29406.0,other,sedan,red,1.0,2018-09-12,50
16872,1,2018.0,jeep grand cherokee,excellent,6.0,gas,15149.0,automatic,SUV,silver,NaN,2018-07-18,21
29030,1,2016.0,chevrolet corvette,excellent,10.0,gas,NaN,other,convertible,black,1.0,2018-08-15,45
11320,1,2019.0,dodge charger,excellent,6.0,gas,18485.0,automatic,sedan,white,1.0,2019-01-03,55
11319,1,2018.0,toyota highlander,excellent,6.0,gas,NaN,automatic,SUV,silver,1.0,2018-09-08,22
11318,1,2017.0,toyota corolla,excellent,4.0,gas,27295.0,automatic,sedan,white,1.0,2019-01-21,17
11317,1,2016.0,toyota tundra,excellent,8.0,gas,23042.0,automatic,truck,black,1.0,2019-03-09,63

In [23]:
# Analisando os veículos mais caros do dataset e exibindo os 17 veículos mais caros

vehicles.sort_values(by='price', ascending=False).head(17)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
12504,375000,1999.0,nissan frontier,good,6.0,gas,115000.0,automatic,pickup,blue,1.0,2018-05-19,21
11359,300000,2015.0,ram 2500,excellent,NaN,diesel,NaN,automatic,truck,grey,1.0,2018-10-15,39
1309,189000,2014.0,ford f-150,good,6.0,gas,151248.0,automatic,truck,black,NaN,2019-03-02,56
27375,189000,2014.0,ford f-150,good,6.0,gas,151248.0,automatic,truck,black,NaN,2018-09-25,72
34389,189000,2014.0,ford f-150,good,6.0,gas,151248.0,automatic,truck,black,NaN,2019-02-02,28
30634,189000,2014.0,ford f-150,good,6.0,gas,NaN,automatic,truck,black,NaN,2018-07-21,42
1668,189000,2014.0,ford f-150,good,6.0,gas,151248.0,automatic,truck,NaN,NaN,2019-03-20,21
33434,189000,2014.0,ford f-150,good,6.0,gas,151248.0,automatic,truck,black,NaN,2019-02-05,102
34206,175000,2004.0,gmc sierra 2500hd,good,8.0,diesel,149000.0,automatic,truck,grey,1.0,2018-08-25,57
41748,145000,2008.0,toyota tundra,like new,NaN,gas,140000.0,automatic,truck,red,1.0,2018-06-16,29
24999,140000,2004.0,ram 2500,good,6.0,diesel,249000.0,automatic,truck,red,1.0,2019-01-22,8
36822,123456,2000.0,chevrolet suburban,good,8.0,gas,NaN,manual,truck,silver,NaN,2018-12-25,33
29810,123456,2000.0,chevrolet suburban,good,8.0,gas,123456.0,manual,truck,silver,NaN,2018-05-09,40
42853,123456,2005.0,chevrolet suburban,fair,NaN,gas,NaN,automatic,SUV,silver,1.0,2019-03-06,21
45263,120000,2006.0,chevrolet silverado 1500,good,8.0,gas,136000.0,automatic,truck,blue,1.0,2018-05-22,27
22833,115000,2012.0,ford f-250 super duty,good,8.0,diesel,225000.0,automatic,truck,white,NaN,2018-12-08,53
20700,109999,NaN,chevrolet corvette,new,8.0,gas,35.0,automatic,coupe,white,NaN,2018-09-07,74

In [24]:
# Removendo duplicatas e filtrando veículos com preço entre 500 e 110000
# Essa filtragem é feita para remover valores extremos, que pela analise exploratória, não tem valores coerentes com o mercado de veículos, e que podem prejudicar a análise dos dados.

vehicles = vehicles.drop_duplicates()
vehicles = vehicles[vehicles['price'].between(500, 110000)].reset_index(drop=True)
vehicles.info()

<class 'pandas.DataFrame'>
RangeIndex: 50440 entries, 0 to 50439
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         50440 non-null  int64
 1   model_year    46888 non-null  float64
 2   model         50440 non-null  str
 3   condition     50440 non-null  str
 4   cylinders     45289 non-null  float64
 5   fuel          50440 non-null  str
 6   odometer      42729 non-null  float64
 7   transmission  50440 non-null  str
 8   type          50440 non-null  str
 9   paint_color   41380 non-null  str
 10  is_4wd        24823 non-null  float64
 11  date_posted   50440 non-null  str
 12  days_listed   50440 non-null  int64
dtypes: float64(4), int64(2), str(7)
memory usage: 7.5 MB

In [25]:
# Criando uma nova coluna 'brand' a partir da coluna 'model', extraindo a primeira palavra de cada modelo como a marca do veículo

vehicles['brand'] = vehicles['model'].str.split().str[0]
vehicles['brand'].value_counts()

brand
ford             12482
chevrolet        10410
toyota            5315
honda             3421
ram               3180
jeep              3166
nissan            3113
gmc               2339
subaru            1269
dodge             1169
hyundai           1165
volkswagen         862
chrysler           831
kia                581
cadillac           322
buick              271
bmw                267
acura              236
mercedes-benz       41
Name: count, dtype: int64

In [26]:
# Analisando a médiana de preço dos veículos por marca e exibindo

vehicles_by_brand = vehicles.groupby('brand')
vehicles_by_brand_median = vehicles_by_brand['price'].median().round(2).sort_values(ascending=False)
print(vehicles_by_brand_median.head(20))

brand
mercedes-benz    34900.0
ram              17990.0
cadillac         13995.0
gmc              13500.0
chevrolet        11980.0
jeep             11900.0
buick             9995.0
ford              9995.0
bmw               9775.0
kia               7995.0
toyota            7900.0
chrysler          7500.0
nissan            7500.0
subaru            7000.0
dodge             7000.0
volkswagen        6872.5
hyundai           6295.0
honda             5995.0
acura             5900.0
Name: price, dtype: float64

In [27]:
# Construindo gráfico de preço mediano por marca

brands = vehicles_by_brand_median.reset_index()
brands = brands.sort_values(by='price')
palette = px.colors.sample_colorscale(
    'Blues',
    [
        0.25 + i * (0.75 / (len(brands) - 1))
        for i in range(len(brands))
    ]
)

fig_brand_bars = px.bar(
    brands,
    x='brand',
    y='price',
    color='brand',
    color_discrete_sequence=palette,
    title='Preço mediano por marca',
    labels={
        'brand': 'Marca',
        'price': 'Preço mediano ($)'
    }
)

fig_brand_bars.update_layout(
    height=600,
    legend_title_text='Marca'
)

fig_brand_bars.show()

In [28]:
# Removendo veículos com odômetro nulo e analisando a verificando a quantidade de valores nulos na coluna 'odometer' após a remoção

vehicles_odometer = vehicles.dropna(subset=['odometer'])
print(vehicles_odometer.isna().sum())

price               0
model_year       3013
model               0
condition           0
cylinders        4356
fuel                0
odometer            0
transmission        0
type                0
paint_color      7639
is_4wd          21658
date_posted         0
days_listed         0
brand               0
dtype: int64

In [29]:
# Construindo gráfico de dispersão entre odômetro e preço

odometer = vehicles_odometer.reset_index(drop=True)

fig_odometer = px.scatter(
    odometer,
    x='odometer',
    y='price',
    title='Relação entre quilometragem e preço',
    labels={
        'odometer': 'Odômetro (milhas)',
        'price': 'Preço ($)'
    },
    opacity=0.18,
    render_mode='webgl',
    log_y=True
)

fig_odometer.update_traces(
    marker=dict(size=4)
)

fig_odometer.update_layout(
    height=650,
    template='plotly_white',
    title_x=0.5,
    xaxis=dict(
        showgrid=True,
        gridcolor='lightgray'
    ),
    yaxis=dict(
        showgrid=True,
        gridcolor='lightgray',
        tickprefix='$'
    )
)

fig_odometer.show()

In [30]:
# Analisando a quantidade de valores nulos na coluna 'model_year' e exibindo o menor e maior ano de fabricação dos veículos

print(vehicles['model_year'].min(), vehicles['model_year'].max())
vehicles['model_year'].isna().sum()

# Removendo veículos com ano de fabricação nulo e filtrando marcas com mais de 1000 veículos no dataset

vehicles_filtered_year = vehicles.dropna(subset=['model_year']).copy()

brand_over_1000 = vehicles_filtered_year['brand'].value_counts()
brand_over_1000 = brand_over_1000[brand_over_1000 >= 1000]
print(brand_over_1000)

# Agrupando os veículos por marca e ano de fabricação, calculando a mediana de preço para cada grupo e exibindo o resultado

vehicles_filtered_year = vehicles_filtered_year[vehicles_filtered_year['brand'].isin(brand_over_1000.index)]
vehicles_grouped_year = vehicles_filtered_year.groupby(['brand', 'model_year'])['price'].median().reset_index()
print(vehicles_grouped_year)

1908.0 2019.0
brand
ford         11610
chevrolet     9703
toyota        4934
honda         3182
ram           2961
jeep          2931
nissan        2879
gmc           2171
subaru        1175
hyundai       1091
dodge         1079
Name: count, dtype: int64
         brand  model_year    price
0    chevrolet      1948.0  21000.0
1    chevrolet      1949.0  44900.0
2    chevrolet      1958.0  36450.0
3    chevrolet      1960.0  20000.0
4    chevrolet      1961.0   5500.0
..         ...         ...      ...
394     toyota      2015.0  16350.0
395     toyota      2016.0  17750.0
396     toyota      2017.0  18999.0
397     toyota      2018.0  25950.0
398     toyota      2019.0  20234.5

[399 rows x 3 columns]

In [31]:
fig_year_bars = px.bar(
    vehicles_grouped_year,
    x='brand',
    y='price',
    barmode='group',
    title='Preço Mediano por Marca e Ano de Fabricação',
    color='model_year',
    color_discrete_sequence=px.colors.sequential.Blues,
    labels={
        'price': 'Preço ($)',
        'brand': 'Marca',
        'model_year': 'Ano de Fabricação'
    },

)

fig_year_bars.update_layout(
    height=800,
    title_x=0.5,
    legend_title_text='Ano de Fabricação',
    yaxis_title='Preço Mediano ($)',
)

fig_year_bars.show()